# Generated by Django 6.0.1 on 2026-03-18 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_remove_produto_preco_produto_motivo_prejuizo_and_more'),
    ]

    operations = [
    migrations.AddField(
        model_name='produto',
        name='excluido',
        field=models.BooleanField(default=False),
    ),
]
