# Generated by Django 6.0.1 on 2026-03-18 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0004_add_excluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='excluido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
