# Generated by Django 6.0.1 on 2026-03-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0005_produto_excluido_em'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_prazo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_vista',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
