# Generated by Django 6.0.1 on 2026-03-22 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0007_produto_descricao_conversao_produto_fator_conversao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='preco_compra_fracionado',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
