# Generated by Django 6.0.1 on 2026-03-23 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0008_produto_preco_compra_fracionado'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='percentual_prazo_fracionado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='percentual_vista_fracionado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_prazo_fracionado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_vista_fracionado',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
