# Generated by Django 6.0.1 on 2026-03-24 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0009_produto_percentual_prazo_fracionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque_minimo',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='preco_compra',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
