# Generated by Django 6.0.1 on 2026-04-23 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0010_alter_produto_estoque_minimo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=60)),
                ('sigla', models.CharField(max_length=20, unique=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
                ('ativa', models.BooleanField(default=True)),
            ],
        ),
    ]
