# Generated by Django 6.0.1 on 2026-04-26 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0015_corrigir_refigerante'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('apelido_nome_conhecido', models.CharField(blank=True, max_length=120, null=True)),
                ('cpf_cnpj', models.CharField(blank=True, max_length=20, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('whatsapp_normalizado', models.CharField(blank=True, max_length=20, null=True)),
                ('telefone_alternativo', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('cep', models.CharField(blank=True, max_length=12, null=True)),
                ('logradouro', models.CharField(blank=True, max_length=140, null=True)),
                ('numero', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento', models.CharField(blank=True, max_length=80, null=True)),
                ('bairro', models.CharField(blank=True, max_length=80, null=True)),
                ('cidade', models.CharField(blank=True, max_length=80, null=True)),
                ('uf', models.CharField(blank=True, max_length=2, null=True)),
                ('referencia', models.CharField(blank=True, max_length=180, null=True)),
                ('tipo_chave_pix', models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ'), ('telefone', 'Telefone'), ('email', 'Email'), ('aleatoria', 'Chave aleatoria'), ('outro', 'Outro')], max_length=20, null=True)),
                ('chave_pix', models.CharField(blank=True, max_length=140, null=True)),
                ('vende_a_prazo', models.BooleanField(default=False)),
                ('prazo_padrao_dias', models.PositiveIntegerField(default=0)),
                ('limite_credito', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('limite_aberto', models.BooleanField(default=False)),
                ('status_credito', models.CharField(choices=[('liberado', 'Liberado'), ('atencao', 'Atencao'), ('bloqueado', 'Bloqueado')], default='liberado', max_length=20)),
                ('observacao_financeira', models.TextField(blank=True, null=True)),
                ('permite_contato_whatsapp', models.BooleanField(default=True)),
                ('nome_contato_whatsapp', models.CharField(blank=True, max_length=120, null=True)),
                ('observacao_contato', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ativo', 'nome'],
            },
        ),
    ]
