# Generated by Django 6.0.1 on 2026-04-28 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0017_venda_itemvenda'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(max_length=60)),
                ('descricao', models.TextField(blank=True)),
                ('canal', models.CharField(blank=True, max_length=40)),
                ('usuario', models.CharField(blank=True, max_length=120, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='estoque.venda')),
            ],
            options={
                'ordering': ['-criado_em', 'id'],
            },
        ),
    ]
