# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0018_eventovenda"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="whatsapp_status",
            field=models.CharField(
                choices=[
                    ("nao_enviado", "WhatsApp ainda nao enviado"),
                    ("aberto", "WhatsApp aberto - aguardando confirmacao"),
                    ("enviado_confirmado", "Nota enviada por WhatsApp"),
                ],
                default="nao_enviado",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="whatsapp_numero_usado",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="whatsapp_aberto_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venda",
            name="whatsapp_confirmado_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
