# Generated by Codex on 2026-04-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0019_venda_whatsapp_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventovenda",
            name="numero_whatsapp",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="eventovenda",
            name="origem_numero",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cadastro", "Cadastro"),
                    ("avulso", "Avulso/manual"),
                    ("desconhecido", "Desconhecido"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
