# Generated by Codex on 2026-04-30

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0020_eventovenda_whatsapp_dados"),
    ]

    operations = [
        migrations.CreateModel(
            name="EntregaRota",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("data", models.DateField(default=django.utils.timezone.localdate)),
                ("tipo", models.CharField(choices=[("unitaria", "Entrega unitaria"), ("rota", "Rota com varias entregas")], max_length=20)),
                ("status", models.CharField(choices=[("aberta", "Aberta"), ("em_carregamento", "Em carregamento"), ("saiu_para_entrega", "Saiu para entrega"), ("concluida", "Concluida")], default="aberta", max_length=30)),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-data", "-id"],
            },
        ),
        migrations.CreateModel(
            name="EntregaRotaItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ordem_entrega", models.PositiveIntegerField(default=1)),
                ("status", models.CharField(choices=[("pendente", "Pendente"), ("carregada", "Carregada"), ("entregue", "Entregue"), ("parcial", "Parcial"), ("cancelada", "Cancelada")], default="pendente", max_length=20)),
                ("observacao", models.TextField(blank=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("rota", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="itens", to="estoque.entregarota")),
                ("venda", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="entregas_rota", to="estoque.venda")),
            ],
            options={
                "ordering": ["ordem_entrega", "id"],
                "unique_together": {("rota", "venda")},
            },
        ),
    ]
