# Generated by Codex on 2026-04-30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0021_entregarota_entregarotaitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="entregarotaitem",
            name="conferido_cliente",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="entregarotaitem",
            name="entrega_concluida",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="EntregaChecklistItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("carregado", models.BooleanField(default=False)),
                ("entregue", models.BooleanField(default=False)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                ("item_venda", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checklists_entrega", to="estoque.itemvenda")),
                ("rota_item", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="checklist_itens", to="estoque.entregarotaitem")),
            ],
            options={
                "ordering": ["item_venda_id"],
                "unique_together": {("rota_item", "item_venda")},
            },
        ),
    ]
