# Generated by Django 6.0.1 on 2026-05-08 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0023_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='entregarotaitem',
            name='is_pendencia',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='entregarotaitem',
            name='origem_pendencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reentregas_pendencia', to='estoque.entregarotaitem'),
        ),
    ]
