# Generated by Django 6.0.1 on 2026-05-08 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0024_entregarotaitem_is_pendencia_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entregarotaitem',
            unique_together={('rota', 'venda', 'is_pendencia')},
        ),
    ]
