# Generated by Django 6.0.1 on 2026-05-12 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0025_entregarotaitem_unique_pendencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='cancelada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='motivo_cancelamento',
            field=models.TextField(blank=True),
        ),
    ]
