# Generated by Django 6.0.1 on 2026-05-12 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0026_venda_cancelada_venda_cancelada_em_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_emissao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_em_aberto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_receber', to='estoque.cliente')),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_receber', to='estoque.venda')),
            ],
            options={
                'ordering': ['data_vencimento', 'id'],
            },
        ),
    ]
