# Generated by Django 6.0.1 on 2026-05-12 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0027_contareceber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('parcial', 'Parcial'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=20),
        ),
        migrations.CreateModel(
            name='RecebimentoContaReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_recebimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('forma_pagamento', models.CharField(blank=True, max_length=80)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recebimentos', to='estoque.contareceber')),
            ],
            options={
                'ordering': ['-data_recebimento', '-id'],
            },
        ),
    ]
