# Generated by Django 6.0.1 on 2026-05-13 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0028_alter_contareceber_status_recebimentocontareceber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('tipo', models.CharField(choices=[('credito_gerado', 'Credito gerado')], default='credito_gerado', max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='estoque.cliente')),
                ('origem_conta_receber', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_gerados', to='estoque.contareceber')),
                ('origem_recebimento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creditos_gerados', to='estoque.recebimentocontareceber')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
