# Generated by Django 6.0.1 on 2026-05-16 18:27

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0029_creditocliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PixRecebido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_pagador', models.CharField(blank=True, max_length=160)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateTimeField(default=django.utils.timezone.now)),
                ('observacao', models.TextField(blank=True)),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='pix/comprovantes/')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('identificado', 'Identificado'), ('baixado', 'Baixado'), ('nao_identificado', 'Nao identificado')], default='pendente', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pix_recebidos', to='estoque.cliente')),
            ],
            options={
                'verbose_name': 'Pix recebido',
                'verbose_name_plural': 'Pix recebidos',
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
    ]
