# Generated by Codex on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0031_pixrecebido_instituicao_pix"),
    ]

    operations = [
        migrations.AddField(
            model_name="pixrecebido",
            name="cliente_sugerido",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pix_sugeridos",
                to="estoque.cliente",
            ),
        ),
        migrations.AddField(
            model_name="pixrecebido",
            name="texto_ocr_bruto",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="pixrecebido",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("identificado", "Identificado"),
                    ("baixado", "Baixado"),
                    ("ignorado", "Ignorado"),
                    ("nao_identificado", "Nao identificado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
