# Generated by Codex on 2026-05-20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0032_pixrecebido_texto_ocr_bruto_status_ignorado"),
    ]

    operations = [
        migrations.AddField(
            model_name="pixrecebido",
            name="pix_original",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="possiveis_duplicados",
                to="estoque.pixrecebido",
            ),
        ),
        migrations.AlterField(
            model_name="pixrecebido",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("identificado", "Identificado"),
                    ("baixado", "Baixado"),
                    ("ignorado", "Ignorado"),
                    ("possivel_duplicado", "Possivel duplicado"),
                    ("nao_identificado", "Nao identificado"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
