# Generated by Codex on 2026-05-20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0033_pixrecebido_possivel_duplicado"),
    ]

    operations = [
        migrations.AddField(
            model_name="pixrecebido",
            name="enviado_por_nome",
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
