# Generated by Codex on 2026-05-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0034_pixrecebido_enviado_por_nome"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pixrecebido",
            name="status",
            field=models.CharField(
                choices=[
                    ("pendente", "Pendente"),
                    ("identificado", "Identificado"),
                    ("baixado", "Baixado"),
                    ("ignorado", "Ignorado"),
                    ("possivel_duplicado", "Possivel duplicado"),
                    ("nao_identificado", "Nao identificado"),
                    ("duplicado", "Duplicado/inativo"),
                ],
                default="pendente",
                max_length=20,
            ),
        ),
    ]
