# Generated by Django 6.0.1 on 2026-06-03 00:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0036_pixrecebido_visualizado_em'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjusteItemVendaQuitada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome_snapshot', models.CharField(max_length=120)),
                ('quantidade_snapshot', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unidade_snapshot', models.CharField(blank=True, max_length=20)),
                ('preco_unitario_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_total_snapshot', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.CharField(choices=[('item_nao_entregue', 'Item nao entregue'), ('cliente_recusou', 'Cliente recusou'), ('produto_faltou', 'Produto faltou'), ('substituicao', 'Substituicao'), ('outro', 'Outro')], max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('diferenca_financeira', models.DecimalField(decimal_places=2, max_digits=12)),
                ('resolucao_financeira', models.CharField(choices=[('nao_definida', 'Nao definida')], default='nao_definida', max_length=30)),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('pendente', 'Pendente'), ('resolvido', 'Resolvido'), ('cancelado', 'Cancelado')], default='pendente', max_length=20)),
                ('operador', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_itens_quitados', to='estoque.cliente')),
                ('item_venda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ajustes_quitados', to='estoque.itemvenda')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ajustes_itens_quitados', to='estoque.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ajustes_itens_quitados', to='estoque.venda')),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
