# Generated by Django 6.0.1 on 2026-06-03 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0037_ajusteitemvendaquitada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ajusteitemvendaquitada',
            name='resolucao_financeira',
            field=models.CharField(choices=[('nao_definida', 'Nao definida'), ('credito_cliente', 'Credito do cliente')], default='nao_definida', max_length=30),
        ),
    ]
