# Generated by Django 6.0.1 on 2026-06-04 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0040_itemvendaremovido_ajuste_origem'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvendaremovido',
            name='estoque_devolvido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemvendaremovido',
            name='estoque_devolvido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venda',
            name='estoque_devolvido_cancelamento',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venda',
            name='estoque_devolvido_cancelamento_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
