# Generated by Django 6.0.1 on 2026-06-04 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0042_alter_ajusteitemvendaquitada_options_pedido_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itempedido',
            options={'ordering': ['id']},
        ),
    ]
