# Generated by Django 6.0.1 on 2026-06-08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0044_funcionario_pode_operar_sistema"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pedido",
            name="status",
            field=models.CharField(
                choices=[
                    ("aberto", "Aberto"),
                    ("cancelado", "Cancelado"),
                    ("parcial", "Parcial"),
                    ("convertido_em_venda", "Convertido em venda"),
                ],
                default="aberto",
                max_length=20,
            ),
        ),
    ]
