# Generated by Django 6.0.1 on 2026-06-12 12:26

import django.db.models.deletion
from django.db import migrations, models


def criar_contatos_de_whatsapp_legado(apps, schema_editor):
    Fornecedor = apps.get_model("estoque", "Fornecedor")
    FornecedorContato = apps.get_model("estoque", "FornecedorContato")

    for fornecedor in Fornecedor.objects.exclude(telefone_whatsapp__isnull=True).exclude(telefone_whatsapp=""):
        telefone = " ".join(str(fornecedor.telefone_whatsapp or "").strip().split())
        if not telefone:
            continue

        FornecedorContato.objects.create(
            fornecedor=fornecedor,
            nome=fornecedor.nome or "Contato principal",
            cargo="Contato principal",
            telefone_whatsapp=telefone,
            telefone_whatsapp_normalizado="".join(caractere for caractere in telefone if caractere.isdigit()) or None,
            principal=True,
            ativo=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0046_compra_fornecedor_contapagar_compra_fornecedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorContato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=140)),
                ('cargo', models.CharField(blank=True, max_length=80, null=True)),
                ('telefone_whatsapp', models.CharField(blank=True, max_length=30, null=True)),
                ('telefone_whatsapp_normalizado', models.CharField(blank=True, max_length=20, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contatos', to='estoque.fornecedor')),
            ],
            options={
                'ordering': ['-principal', '-ativo', 'nome', 'id'],
            },
        ),
        migrations.RunPython(criar_contatos_de_whatsapp_legado, migrations.RunPython.noop),
    ]
