# Generated by Django 6.0.1 on 2026-06-14 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0047_fornecedorcontato'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='forma_pagamento_padrao',
            field=models.CharField(choices=[('avista', 'À vista'), ('aprazo', 'A prazo')], default='avista', max_length=20),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='prazos_pagamento_padrao',
            field=models.CharField(blank=True, help_text='Exemplo: 7, 14, 21', max_length=120, null=True),
        ),
    ]
