# Generated by Django 6.0.1 on 2026-06-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0048_fornecedor_forma_pagamento_padrao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='dia_vencimento_cartao',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='forma_pagamento_padrao',
            field=models.CharField(choices=[('avista', 'À vista'), ('aprazo', 'A prazo / boleto'), ('cartao', 'Cartão de crédito')], default='avista', max_length=20),
        ),
    ]
