# Generated by Django 6.0.1 on 2026-06-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0049_fornecedor_dia_vencimento_cartao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='aceita_boleto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='aceita_cartao_credito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='aceita_cartao_debito',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='aceita_dinheiro',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='aceita_pix',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='forma_pagamento_padrao',
            field=models.CharField(choices=[('avista', 'À vista'), ('pix', 'Pix'), ('dinheiro', 'Dinheiro'), ('debito', 'Cartão de débito'), ('cartao', 'Cartão de crédito'), ('aprazo', 'Boleto / a prazo')], default='avista', max_length=20),
        ),
    ]
