# Generated by Django 6.0.1 on 2026-06-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0050_fornecedor_aceita_boleto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeioPagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('debito', 'Cartão de débito'), ('credito', 'Cartão de crédito'), ('transferencia', 'Transferência'), ('boleto', 'Boleto / a prazo'), ('outro', 'Outro')], max_length=30)),
                ('banco_ou_pessoa', models.CharField(blank=True, max_length=120, null=True)),
                ('dia_vencimento_cartao', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('principal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-ativo', 'tipo', '-principal', 'nome', 'id'],
            },
        ),
    ]
