# Generated by Django 6.0.1 on 2026-06-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0051_meiopagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meiopagamento',
            name='tipo',
            field=models.CharField(choices=[('credito', 'Cartão de crédito'), ('debito', 'Cartão de débito'), ('outro', 'Outro cartão')], max_length=30),
        ),
    ]
