# Generated by Django 6.0.1 on 2026-06-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0052_alter_meiopagamento_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='meiopagamento',
            name='dono_titular',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='meiopagamento',
            name='final_cartao',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
