# Generated by Django 6.0.1 on 2026-06-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0053_meiopagamento_dono_titular_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentocontapagar',
            name='juros_bancarios',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
