# Generated by Django 6.0.1 on 2026-06-16 19:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0054_pagamentocontapagar_juros_bancarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaDiaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(default=django.utils.timezone.now)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('categoria', models.CharField(choices=[('gasolina', 'Gasolina'), ('alimentacao', 'Lanche / Alimentacao'), ('gelo', 'Gelo'), ('estacionamento', 'Estacionamento'), ('frete_entrega', 'Frete / Entrega'), ('ajudante_diaria', 'Ajudante / Diaria'), ('manutencao', 'Manutencao'), ('material_apoio', 'Material de apoio'), ('compra_emergencial', 'Compra emergencial'), ('outros', 'Outros')], max_length=40)),
                ('forma_pagamento', models.CharField(choices=[('Pix', 'Pix'), ('Dinheiro', 'Dinheiro'), ('Cartao', 'Cartao'), ('Boleto', 'Boleto'), ('Transferencia', 'Transferencia'), ('Outro', 'Outro')], default='Pix', max_length=40)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-data_hora', '-id'],
            },
        ),
    ]
