# Generated by Django 6.0.1 on 2026-06-17 01:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0056_contafinanceira_movimentofinanceiro'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestimoDivida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('emprestimo_recebido', 'Emprestimo recebido'), ('divida_avulsa', 'Divida avulsa'), ('financiamento', 'Financiamento'), ('outro', 'Outro')], max_length=30)),
                ('credor', models.CharField(max_length=150)),
                ('descricao', models.CharField(blank=True, max_length=255)),
                ('valor_original', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_devedor', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('data_contratacao', models.DateField()),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('quantidade_parcelas', models.PositiveIntegerField(blank=True, null=True)),
                ('valor_parcela', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('parcial', 'Parcial'), ('quitado', 'Quitado'), ('cancelado', 'Cancelado')], default='aberto', max_length=20)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['status', 'data_vencimento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PagamentoEmprestimoDivida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_pagamento', models.DateField()),
                ('forma_pagamento', models.CharField(blank=True, max_length=50)),
                ('observacao', models.CharField(blank=True, max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('divida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='estoque.emprestimodivida')),
            ],
            options={
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
    ]
