# Generated by Django 6.0.1 on 2026-06-17 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0057_emprestimodivida_pagamentoemprestimodivida'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentofinanceiro',
            name='operador',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
