# Generated by Django 6.0.1 on 2026-06-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0058_movimentofinanceiro_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='pode_operar_caixa',
            field=models.BooleanField(default=False),
        ),
    ]
