# Generated by Django 6.0.1 on 2026-06-17 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0060_alter_produto_quantidade'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmprestimoRapido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pessoa_nome', models.CharField(max_length=150)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_emprestimo', models.DateField()),
                ('previsao_devolucao', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('quitado', 'Quitado')], default='aberto', max_length=20)),
                ('data_quitacao', models.DateField(blank=True, null=True)),
                ('valor_devolvido', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('observacao_quitacao', models.TextField(blank=True)),
                ('operador', models.CharField(blank=True, max_length=120)),
                ('operador_quitacao', models.CharField(blank=True, max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('conta_entrada_quitacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_rapidos_quitacao', to='estoque.contafinanceira')),
                ('conta_saida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos_rapidos_saida', to='estoque.contafinanceira')),
            ],
            options={
                'ordering': ['status', '-data_emprestimo', '-id'],
            },
        ),
    ]
