# Generated by Django 6.0.1 on 2026-06-18 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0061_emprestimorapido'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentofinanceiro',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to='estoque.compra'),
        ),
    ]
