# Generated by Django 6.0.1 on 2026-06-19 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0062_movimentofinanceiro_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='fechamento_token',
            field=models.CharField(blank=True, editable=False, max_length=32, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name='movimentofinanceiro',
            constraint=models.UniqueConstraint(condition=models.Q(('compra__isnull', False), ('origem', 'compra_a_vista')), fields=('compra', 'conta', 'origem'), name='movimento_unico_compra_avista_conta'),
        ),
    ]
