# Generated by Django 6.0.1 on 2026-06-21 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0063_compra_fechamento_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesadiaria',
            name='categoria',
            field=models.CharField(choices=[('gasolina', 'Gasolina'), ('alimentacao', 'Lanche / Alimentacao'), ('gelo', 'Gelo'), ('estacionamento', 'Estacionamento'), ('frete_entrega', 'Frete / Entrega'), ('ajudante_diaria', 'Ajudante / Diaria'), ('manutencao', 'Manutencao'), ('material_apoio', 'Material de apoio'), ('compra_emergencial', 'Compra emergencial'), ('pessoal', 'Despesa pessoal'), ('outros', 'Outros')], max_length=40),
        ),
    ]
