# Generated by Django 6.0.1 on 2026-06-21 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0064_alter_despesadiaria_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesadiaria',
            name='operador',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
