# Generated by Django 6.0.1 on 2026-06-26 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0065_despesadiaria_operador'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='cadastro_incompleto',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compra',
            name='status',
            field=models.CharField(choices=[('aberta', 'Aberta'), ('rascunho', 'Rascunho'), ('finalizacao_iniciada', 'Finalizacao iniciada'), ('cancelada', 'Cancelada'), ('finalizada', 'Finalizada')], default='aberta', max_length=20),
        ),
    ]
