# Generated by Django 6.0.1 on 2026-06-29 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0066_produto_cadastro_incompleto_alter_compra_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtofornecedor',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='produtofornecedor',
            name='fornecedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos_vinculados', to='estoque.fornecedor'),
        ),
        migrations.AlterField(
            model_name='produtofornecedor',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fornecedores_vinculados', to='estoque.produto'),
        ),
    ]
