# Generated by Django 6.0.1 on 2026-06-30 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0067_produtofornecedor_ativo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListaCompraFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_lista', models.DateField()),
                ('data_inicio_periodo', models.DateField()),
                ('data_fim_periodo', models.DateField()),
                ('data_chegada_prevista', models.DateField(blank=True, null=True)),
                ('total_sugerido_original', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_lista', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacao', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('enviada', 'Enviada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='aberta', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listas_compra', to='estoque.fornecedor')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='ItemListaCompraFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque_atual', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('estoque_minimo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('vendido_periodo', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('pedidos_abertos', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantidade_sugerida', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('quantidade_final', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unidade', models.CharField(blank=True, max_length=20)),
                ('preco_compra', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('preco_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_lista_compra_fornecedor', to='estoque.produto')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.listacomprafornecedor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
