# Generated by Django 6.0.1 on 2026-07-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0068_listacomprafornecedor_itemlistacomprafornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemlistacomprafornecedor',
            name='conferido',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='itemlistacomprafornecedor',
            name='conferido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemlistacomprafornecedor',
            name='observacao_conferencia',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='itemlistacomprafornecedor',
            name='quantidade_recebida',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='itemlistacomprafornecedor',
            name='status_conferencia',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('ok', 'OK'), ('faltou', 'Faltou'), ('veio_a_mais', 'Veio a mais'), ('nao_veio', 'Nao veio')], default='pendente', max_length=20),
        ),
    ]
