# Generated by Django 6.0.1 on 2026-07-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0069_itemlistacomprafornecedor_conferido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacomprafornecedor',
            name='classificacao_diferenca_nota',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='listacomprafornecedor',
            name='observacao_diferenca_nota',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='listacomprafornecedor',
            name='valor_nota_boleto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
