# Generated by Django 6.0.1 on 2026-07-05 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0070_listacomprafornecedor_classificacao_diferenca_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacomprafornecedor',
            name='forma_cobranca_nota',
            field=models.CharField(blank=True, choices=[('', 'Não informada'), ('avista', 'À vista'), ('boleto_unico', 'Boleto único'), ('varios_boletos', 'Vários boletos')], default='', max_length=30),
        ),
        migrations.AddField(
            model_name='listacomprafornecedor',
            name='observacao_pagamento_nota',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.CreateModel(
            name='ParcelaNotaListaCompraFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(default=1)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observacao', models.CharField(blank=True, default='', max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_nota', to='estoque.listacomprafornecedor')),
            ],
            options={
                'ordering': ['numero', 'id'],
            },
        ),
    ]
