# Generated by Django 6.0.1 on 2026-07-07 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0071_listacomprafornecedor_forma_cobranca_nota_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listacomprafornecedor',
            name='checklist_externa_conferente',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='listacomprafornecedor',
            name='checklist_externa_token_expira_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listacomprafornecedor',
            name='checklist_externa_token_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='listacomprafornecedor',
            name='checklist_externa_token_usado_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
