# Generated by Django 6.0.1 on 2026-07-12 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0072_listacomprafornecedor_checklist_externa_conferente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='frequencia_visita_ativa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='frequencia_visita_data_referencia',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='frequencia_visita_dia_semana',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Segunda-feira'), (1, 'Terca-feira'), (2, 'Quarta-feira'), (3, 'Quinta-feira'), (4, 'Sexta-feira'), (5, 'Sabado'), (6, 'Domingo')], null=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='frequencia_visita_intervalo_dias',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listacomprafornecedor',
            name='data_visita_fornecedor',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
