# Generated by Django 6.0.1 on 2026-07-13 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0073_fornecedor_frequencia_visita_ativa_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorContatoTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('tipo', models.CharField(choices=[('celular', 'Celular'), ('fixo', 'Fixo'), ('outro', 'Outro')], default='celular', max_length=20)),
                ('whatsapp', models.BooleanField(default=False)),
                ('principal', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveSmallIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='estoque.fornecedorcontato')),
            ],
            options={
                'ordering': ['-principal', 'ordem', 'id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True)), fields=('contato', 'numero'), name='uniq_fornecedor_contato_telefone_ativo'), models.UniqueConstraint(condition=models.Q(('ativo', True), ('principal', True)), fields=('contato',), name='uniq_fornecedor_contato_telefone_principal')],
            },
        ),
    ]
