# Generated by Django 6.0.1 on 2026-07-14 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0075_migrar_telefones_contatos_fornecedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorDestinatarioLista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('padrao', 'Padr?o'), ('temporario', 'Tempor?rio')], default='padrao', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('vigencia_inicio', models.DateField(blank=True, null=True)),
                ('vigencia_fim', models.DateField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('contato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinatarios_lista', to='estoque.fornecedorcontato')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios_lista', to='estoque.fornecedor')),
                ('telefone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destinatarios_lista', to='estoque.fornecedorcontatotelefone')),
            ],
            options={
                'ordering': ['-ativo', 'tipo', '-criado_em', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ativo', True), ('tipo', 'padrao')), fields=('fornecedor',), name='uniq_destinatario_lista_padrao_ativo'), models.UniqueConstraint(condition=models.Q(('ativo', True), ('tipo', 'temporario')), fields=('fornecedor',), name='uniq_destinatario_lista_temporario_ativo')],
            },
        ),
    ]
