# Generated by Django 6.0.1 on 2026-07-14 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0076_fornecedordestinatariolista'),
    ]

    operations = [
        migrations.CreateModel(
            name='FornecedorDestinatarioRecente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, default='', max_length=140)),
                ('telefone', models.CharField(max_length=20)),
                ('ultima_utilizacao', models.DateTimeField(db_index=True)),
                ('quantidade_utilizacoes', models.PositiveIntegerField(default=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios_recentes_lista', to='estoque.fornecedor')),
            ],
            options={
                'ordering': ['-ultima_utilizacao', '-id'],
                'constraints': [models.UniqueConstraint(fields=('fornecedor', 'telefone'), name='uniq_destinatario_recente_fornecedor_telefone')],
            },
        ),
    ]
