# Generated by Django 6.0.1 on 2026-07-14 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0077_fornecedordestinatariorecente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioListaCompraFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_destinatario', models.CharField(blank=True, default='', max_length=140)),
                ('telefone_destinatario', models.CharField(max_length=20)),
                ('confirmado_em', models.DateTimeField(db_index=True)),
                ('origem_destinatario', models.CharField(choices=[('padrao', 'Destinatario padrao'), ('recente', 'Destinatario recente'), ('personalizado', 'Destinatario personalizado')], default='personalizado', max_length=20)),
                ('chave_idempotencia', models.CharField(db_index=True, max_length=80, unique=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_listas_compra_confirmados', to=settings.AUTH_USER_MODEL)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_listas_compra', to='estoque.fornecedor')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_vendedor', to='estoque.listacomprafornecedor')),
            ],
            options={
                'ordering': ['-confirmado_em', '-id'],
                'indexes': [models.Index(fields=['lista', '-confirmado_em'], name='idx_envio_lista_conf_em'), models.Index(fields=['fornecedor', '-confirmado_em'], name='idx_envio_forn_conf_em')],
            },
        ),
    ]
