# Generated by Django 6.0.1 on 2026-07-15 10:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0078_enviolistacomprafornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResolucaoVisitaFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_visita_original', models.DateField(db_index=True)),
                ('tipo_resolucao', models.CharField(choices=[('nao_ocorreu', 'Visita nao ocorreu'), ('adiada', 'Visita adiada'), ('ignorar_ciclo', 'Ignorar este ciclo')], max_length=20)),
                ('nova_data_visita', models.DateField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True, default='')),
                ('resolvido_em', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='resolucoes_visitas', to='estoque.fornecedor')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolucoes_visitas_fornecedores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-resolvido_em', '-id'],
                'indexes': [models.Index(fields=['fornecedor', 'data_visita_original'], name='idx_resolucao_visita_ciclo'), models.Index(fields=['tipo_resolucao', '-resolvido_em'], name='idx_resolucao_tipo_data')],
                'constraints': [models.UniqueConstraint(fields=('fornecedor', 'data_visita_original'), name='uniq_resolucao_ciclo_visita_fornecedor')],
            },
        ),
    ]
