# Generated by Django 6.0.1 on 2026-07-20 06:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0079_resolucaovisitafornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnvioInternoListaCompraFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('versao', models.CharField(choices=[('analitica', 'Analitica'), ('sintetica', 'Sintetica')], default='analitica', max_length=20)),
                ('nome_destinatario', models.CharField(blank=True, default='', max_length=140)),
                ('telefone_destinatario', models.CharField(blank=True, default='', max_length=20)),
                ('origem_destinatario', models.CharField(choices=[('funcionario', 'Funcionario'), ('avulso', 'Numero avulso'), ('sem_numero', 'Sem numero')], default='sem_numero', max_length=20)),
                ('registrado_em', models.DateTimeField(db_index=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='envios_internos_listas_compra', to='estoque.fornecedor')),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_internos_listas_compra', to='estoque.funcionario')),
                ('lista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='envios_internos', to='estoque.listacomprafornecedor')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='envios_internos_listas_compra_registrados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-registrado_em', '-id'],
                'indexes': [models.Index(fields=['lista', '-registrado_em'], name='idx_envio_int_lista_em'), models.Index(fields=['fornecedor', '-registrado_em'], name='idx_envio_int_forn_em')],
            },
        ),
    ]
