# Generated by Django 6.0.1 on 2026-07-21 00:00

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0080_enviointernolistacomprafornecedor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoRecebimentoCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente_nome_snapshot', models.CharField(max_length=160)),
                ('valor_recebido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_aplicado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('credito_gerado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saldo_atual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_recebimento', models.DateField()),
                ('forma_pagamento', models.CharField(max_length=80)),
                ('rota_snapshot', models.CharField(blank=True, max_length=160)),
                ('status_recibo', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('dispensado', 'Dispensado')], default='pendente', max_length=20)),
                ('comprovante_dados', models.JSONField(blank=True, default=dict)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('recibo_confirmado_em', models.DateTimeField(blank=True, null=True)),
                ('recibo_dispensado_em', models.DateTimeField(blank=True, null=True)),
                ('motivo_dispensa', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_recebimento', to='estoque.cliente')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_recebimento_criadas', to=settings.AUTH_USER_MODEL)),
                ('recibo_confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_recebimento_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('recibo_dispensado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operacoes_recebimento_dispensadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Operacao de recebimento de cliente',
                'verbose_name_plural': 'Operacoes de recebimento de clientes',
                'ordering': ['-criado_em', '-id'],
            },
        ),
        migrations.AddField(
            model_name='recebimentocontareceber',
            name='operacao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recebimentos', to='estoque.operacaorecebimentocliente'),
        ),
    ]
