# Generated by Django 6.0.1 on 2026-07-23 16:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0081_operacaorecebimentocliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FechamentoRotaRecebimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rota', models.CharField(max_length=160)),
                ('data_referencia', models.DateField()),
                ('metodo_conferencia', models.CharField(choices=[('cedulas', 'Cedulas'), ('direta', 'Direta')], default='direta', max_length=20)),
                ('status', models.CharField(choices=[('aberto', 'Aberto'), ('conferido', 'Conferido'), ('finalizado', 'Finalizado')], default='aberto', max_length=20)),
                ('total_sistema', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_conferido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('diferenca', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('observacao', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_rota_recebimento_criados', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fechamentos_rota_recebimento', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fechamento de recebimentos da rota',
                'verbose_name_plural': 'Fechamentos de recebimentos da rota',
                'ordering': ['-data_referencia', 'rota', '-id'],
            },
        ),
    ]
