# Generated by Django 6.0.1 on 2026-07-24 12:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0082_fechamentorotarecebimento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentorotarecebimento',
            name='composicao_cedulas',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddConstraint(
            model_name='fechamentorotarecebimento',
            constraint=models.UniqueConstraint(fields=('rota', 'data_referencia'), name='uniq_fechamento_rota_recebimento_data'),
        ),
    ]
