# Generated by Django 6.0.1 on 2026-07-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0083_fechamentorotarecebimento_composicao_cedulas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fechamentorotarecebimento',
            name='metodo_conferencia',
            field=models.CharField(choices=[('cedulas', 'Cédulas'), ('direta', 'Direta')], default='direta', max_length=20),
        ),
    ]
