# Generated by Django 6.0.1 on 2026-07-27 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0084_alter_fechamentorotarecebimento_metodo_conferencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='codigo_legado',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='documento_legado',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contareceber',
            name='numero_legado',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='codigo_legado',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True),
        ),
    ]
