# Generated by Django 6.0.1 on 2026-07-27 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0085_cliente_codigo_legado_contapagar_documento_legado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='codigo_legado',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
    ]
