# Generated by Django 6.0.1 on 2026-07-27 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0086_produto_codigo_legado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contareceber',
            name='venda',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conta_receber', to='estoque.venda'),
        ),
    ]
