# Generated by Django 6.0.1 on 2026-07-29 07:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0087_alter_contareceber_venda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroCobrancaCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('manual', 'Manual'), ('whatsapp', 'WhatsApp'), ('telefone', 'Telefone'), ('visita', 'Visita'), ('outro', 'Outro')], default='manual', max_length=20)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('contatado', 'Contatado'), ('promessa_pagamento', 'Promessa de pagamento'), ('sem_resposta', 'Sem resposta'), ('resolvido', 'Resolvido')], default='pendente', max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_cobranca', to='estoque.cliente')),
                ('conta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_cobranca', to='estoque.contareceber')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_cobranca_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de cobranca de cliente',
                'verbose_name_plural': 'Registros de cobranca de clientes',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
