# Generated by Django 6.0.1 on 2026-08-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0091_itemvenda_estoque_antes_itemvenda_estoque_depois_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvendaremovido',
            name='estoque_antes',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='itemvendaremovido',
            name='estoque_depois',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='itemvendaremovido',
            name='estoque_movimentado',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='itemvendaremovido',
            name='estoque_unidade_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
