# Generated by Django 6.0.1 on 2026-09-02 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0092_itemvendaremovido_estoque_antes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contapagar',
            name='compra',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conta_pagar', to='estoque.compra'),
        ),
    ]
