# Generated by Django 6.0.1 on 2026-09-05 13:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0093_alter_contapagar_compra'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='estoque_conferido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_conferido_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produto',
            name='estoque_conferido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produtos_conferidos_estoque', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='MovimentacaoEstoqueManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('conferencia', 'Conferencia'), ('ajuste', 'Ajuste manual')], max_length=20)),
                ('estoque_antes', models.DecimalField(decimal_places=3, max_digits=12)),
                ('estoque_depois', models.DecimalField(decimal_places=3, max_digits=12)),
                ('diferenca', models.DecimalField(decimal_places=3, max_digits=12)),
                ('motivo', models.TextField(blank=True)),
                ('observacao', models.TextField(blank=True)),
                ('operador_nome', models.CharField(blank=True, max_length=150)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentacoes_estoque_manuais', to='estoque.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentacoes_estoque_manuais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
