# Generated by Django 6.0.1 on 2026-09-08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0094_produto_estoque_conferido_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="preco_conferido",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_conferido_em",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="preco_conferido_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="produtos_conferidos_preco",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
