# Generated by Django 6.0.1 on 2026-09-09 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0095_produto_preco_conferido'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='despesadiaria',
            name='data_rota_recebimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='despesadiaria',
            name='paga_com_dinheiro_rota',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='despesadiaria',
            name='rota_recebimento',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.CreateModel(
            name='DespesaRotaConferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_justificado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('confirmado_em', models.DateTimeField(auto_now_add=True)),
                ('confirmado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='despesas_rota_conferencia_confirmadas', to=settings.AUTH_USER_MODEL)),
                ('despesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='confirmacoes_rota', to='estoque.despesadiaria')),
                ('fechamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='despesas_rota_confirmadas', to='estoque.fechamentorotarecebimento')),
            ],
            options={
                'ordering': ['fechamento_id', 'despesa_id'],
                'constraints': [models.UniqueConstraint(fields=('fechamento', 'despesa'), name='uniq_despesa_rota_conferencia_fechamento')],
            },
        ),
    ]
