# Generated by Django 6.0.1 on 2026-09-13 01:30

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0097_compra_total_produtos_ajuste_total'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeparacaoVenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('enviada', 'Enviada'), ('em_separacao', 'Em separacao'), ('separada', 'Separada'), ('com_pendencia', 'Com pendencia'), ('cancelada', 'Cancelada')], default='enviada', max_length=30)),
                ('enviado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('iniciado_em', models.DateTimeField(blank=True, null=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separacoes_venda_enviadas', to=settings.AUTH_USER_MODEL)),
                ('separado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separacoes_venda_realizadas', to=settings.AUTH_USER_MODEL)),
                ('venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='separacao', to='estoque.venda')),
            ],
            options={
                'ordering': ['enviado_em', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SeparacaoVendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome_snapshot', models.CharField(max_length=120)),
                ('unidade_snapshot', models.CharField(blank=True, max_length=20)),
                ('quantidade_solicitada', models.DecimalField(decimal_places=3, max_digits=12)),
                ('quantidade_separada', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('conferido', 'OK'), ('nao_encontrado', 'Nao encontrado'), ('quantidade_insuficiente', 'Quantidade insuficiente')], default='pendente', max_length=30)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item_venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='separacoes', to='estoque.itemvenda')),
                ('separacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='estoque.separacaovenda')),
            ],
            options={
                'ordering': ['item_venda_id'],
                'unique_together': {('separacao', 'item_venda')},
            },
        ),
    ]
