# Generated by Django 6.0.1 on 2026-09-13 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0098_separacaovenda_separacaovendaitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='separacaovenda',
            name='responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separacoes_venda_responsavel', to='estoque.funcionario'),
        ),
    ]
