# Generated by Codex on 2026-09-13

import django.utils.timezone
from django.db import migrations, models


def preencher_sequencias_existentes(apps, schema_editor):
    SeparacaoVenda = apps.get_model("estoque", "SeparacaoVenda")
    contadores = {}
    separacoes = SeparacaoVenda.objects.order_by("enviado_em", "id")
    for separacao in separacoes:
        data_sequencia = django.utils.timezone.localtime(separacao.enviado_em).date()
        proximo_numero = contadores.get(data_sequencia, 0) + 1
        contadores[data_sequencia] = proximo_numero
        separacao.data_sequencia = data_sequencia
        separacao.numero_sequencial_dia = proximo_numero
        separacao.save(update_fields=["data_sequencia", "numero_sequencial_dia"])


class Migration(migrations.Migration):

    dependencies = [
        ("estoque", "0099_separacaovenda_responsavel"),
    ]

    operations = [
        migrations.AddField(
            model_name="separacaovenda",
            name="data_sequencia",
            field=models.DateField(default=django.utils.timezone.localdate, null=True),
        ),
        migrations.AddField(
            model_name="separacaovenda",
            name="numero_sequencial_dia",
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.RunPython(preencher_sequencias_existentes, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="separacaovenda",
            name="data_sequencia",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="separacaovenda",
            name="numero_sequencial_dia",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name="separacaovenda",
            constraint=models.UniqueConstraint(
                fields=("data_sequencia", "numero_sequencial_dia"),
                name="uniq_separacao_venda_sequencia_dia",
            ),
        ),
    ]
