# Generated by Django 6.0.1 on 2026-09-17 07:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0101_pendenciapedidoencerrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='lista_fornecedor',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compra_vinculada', to='estoque.listacomprafornecedor'),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='numero_parcela',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contapagar',
            name='total_parcelas',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contapagar',
            name='compra',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contas_pagar', to='estoque.compra'),
        ),
    ]
