# Generated by Django 6.0.1 on 2026-09-17 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0102_compra_lista_fornecedor_contapagar_numero_parcela_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='separacaovenda',
            name='revisao_concluida_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='separacaovenda',
            name='revisao_pendente',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='separacaovenda',
            name='revisao_solicitada_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='separacaovenda',
            name='teve_revisao',
            field=models.BooleanField(default=False),
        ),
    ]
