# Generated by Django 6.0.1 on 2026-09-18 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0104_itemvenda_custo_origem_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemvendaremovido',
            name='custo_origem_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='itemvendaremovido',
            name='custo_total_snapshot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='itemvendaremovido',
            name='custo_unidade_snapshot',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='itemvendaremovido',
            name='custo_unitario_snapshot',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
    ]
