# Generated by Django 6.0.1 on 2026-09-19 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0105_itemvendaremovido_custo_origem_snapshot_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='separacaovendaitem',
            name='item_venda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='separacoes', to='estoque.itemvenda'),
        ),
    ]
