# Generated by Django 6.0.1 on 2026-09-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0106_alter_separacaovendaitem_item_venda'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoDespesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('empresa', 'Empresa'), ('pessoal', 'Pessoal')], max_length=20)),
                ('grupo', models.CharField(max_length=80)),
                ('categoria', models.CharField(max_length=80)),
                ('favorito', models.BooleanField(default=False)),
                ('ativo', models.BooleanField(default=True)),
                ('ordem', models.PositiveIntegerField(default=100)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Item do catalogo de despesas',
                'verbose_name_plural': 'Catalogo de despesas',
                'ordering': ['ordem', 'tipo', 'grupo', 'nome'],
            },
        ),
    ]
