# Generated by Django 6.0.1 on 2026-09-19 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0107_catalogodespesa'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesadiaria',
            name='catalogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lancamentos', to='estoque.catalogodespesa'),
        ),
    ]
