# Generated by Django 6.0.1 on 2026-09-19 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0109_catalogo_despesas_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogodespesa',
            name='pessoa',
            field=models.CharField(blank=True, help_text='Lincoln, Roseli ou Familia quando for despesa pessoal.', max_length=80),
        ),
    ]
