# Generated by Django 6.0.1 on 2026-09-20 13:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0114_reorganiza_catalogo_empresa_e_funcionario'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaoCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('titular', models.CharField(max_length=120)),
                ('dia_fechamento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dia_vencimento', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['titular', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='FaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_fechamento', models.DateField(blank=True, null=True)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('aberta', 'Aberta'), ('fechada', 'Fechada'), ('parcial', 'Parcial'), ('paga', 'Paga')], default='aberta', max_length=20)),
                ('valor_pago', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='faturas', to='estoque.cartaocredito')),
            ],
            options={
                'ordering': ['data_vencimento', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LancamentoCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('descricao', models.CharField(max_length=255)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('compra', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_cartao', to='estoque.compra')),
                ('despesa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos_cartao', to='estoque.despesadiaria')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='estoque.faturacartao')),
            ],
            options={
                'ordering': ['data', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='faturacartao',
            constraint=models.UniqueConstraint(fields=('cartao', 'data_vencimento'), name='fatura_cartao_vencimento_unico'),
        ),
        migrations.AddConstraint(
            model_name='lancamentocartao',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('compra__isnull', False), ('despesa__isnull', True)), models.Q(('compra__isnull', True), ('despesa__isnull', False)), _connector='OR'), name='lancamento_cartao_uma_origem'),
        ),
        migrations.AddConstraint(
            model_name='lancamentocartao',
            constraint=models.UniqueConstraint(condition=models.Q(('compra__isnull', False)), fields=('compra',), name='lancamento_cartao_compra_unica'),
        ),
        migrations.AddConstraint(
            model_name='lancamentocartao',
            constraint=models.UniqueConstraint(condition=models.Q(('despesa__isnull', False)), fields=('despesa',), name='lancamento_cartao_despesa_unica'),
        ),
    ]
