# Generated by Django 6.0.1 on 2026-09-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0115_cartaocredito_faturacartao_lancamentocartao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='despesadiaria',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='despesas', to='estoque.cartaocredito'),
        ),
    ]
