# Generated by Django 6.0.1 on 2026-09-20 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0116_despesadiaria_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='compras', to='estoque.cartaocredito'),
        ),
    ]
