# Generated by Django 6.0.1 on 2026-09-20 19:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0117_compra_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lancamentocartao',
            name='cartao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='estoque.cartaocredito'),
        ),
        migrations.AlterField(
            model_name='lancamentocartao',
            name='fatura',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lancamentos', to='estoque.faturacartao'),
        ),
    ]
