# Generated by Django 6.0.1 on 2026-09-20 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0118_lancamento_cartao_pendente'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoFaturaCartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pagamento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('operador', models.CharField(blank=True, max_length=120)),
                ('observacao', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos_fatura_cartao', to='estoque.contafinanceira')),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagamentos', to='estoque.faturacartao')),
                ('movimento', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='pagamento_fatura_cartao', to='estoque.movimentofinanceiro')),
            ],
            options={
                'ordering': ['-data_pagamento', '-id'],
            },
        ),
    ]
