# Generated by Django 6.0.1 on 2026-09-23 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0121_corrige_unidade_legada_pc_para_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='fechamentorotarecebimento',
            name='conferido_por_funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='fechamentos_rota_conferidos', to='estoque.funcionario'),
        ),
    ]
