# Generated by Django 6.0.1 on 2026-10-02 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0125_pagamentocontapagar_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='compra',
            name='revisao_precos_pendente',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
