# Generated by Django 6.0.1 on 2026-10-03 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0129_snapshots_precos_compra'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoProdutoVinculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MembroGrupoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='estoque.grupoprodutovinculado')),
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vinculo_grupo', to='estoque.produto')),
            ],
        ),
        migrations.AddField(
            model_name='grupoprodutovinculado',
            name='produtos',
            field=models.ManyToManyField(related_name='grupos_vinculados', through='estoque.MembroGrupoProduto', to='estoque.produto'),
        ),
    ]
