# Generated by Django 6.0.1 on 2026-10-09 17:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def criar_controle(apps, schema_editor):
    apps.get_model('estoque', 'ControlePrecosVinculados').objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0130_grupos_produtos_vinculados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlePrecosVinculados',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.RunPython(criar_controle, migrations.RunPython.noop),
        migrations.AddField(
            model_name='grupoprodutovinculado',
            name='precos_regularizados',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name='grupoprodutovinculado',
            name='ultima_alteracao_precos',
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='grupoprodutovinculado',
            name='versao_precos',
            field=models.PositiveBigIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='itemcompra',
            name='alteracoes_precos_vinculados',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.AddField(
            model_name='compra',
            name='alteracoes_precos_vinculados',
            field=models.JSONField(blank=True, default=list, editable=False),
        ),
        migrations.CreateModel(
            name='AlteracaoPrecoVinculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('grupo_id_snapshot', models.PositiveBigIntegerField()),
                ('grupo_nome_snapshot', models.CharField(max_length=120)),
                ('origem', models.CharField(max_length=80)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('versao_antes', models.PositiveBigIntegerField()),
                ('versao_depois', models.PositiveBigIntegerField()),
                ('evento_anterior', models.UUIDField(null=True)),
                ('reverte', models.UUIDField(null=True, unique=True)),
                ('evidencia', models.JSONField()),
                ('operador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
