from django.urls import path
from . import views

app_name = "estoque"

urlpatterns = [
    path("", views.home, name="home"),
    path("painel-financeiro/", views.painel_financeiro, name="painel_financeiro"),
    path("caixa-banco/", views.caixa_banco, name="caixa_banco"),
    path(
        "caixa-banco/movimentos/<int:movimento_id>/editar-descricao/",
        views.caixa_banco_editar_descricao_movimento,
        name="caixa_banco_editar_descricao_movimento",
    ),
    path("despesas-diarias/", views.despesas_diarias, name="despesas_diarias"),
    path("cadastrar/", views.cadastrar_produto, name="cadastrar_produto"),
    path("cadastrar-unidade/", views.cadastrar_unidade, name="cadastrar_unidade"),
    path("unidades/", views.unidades_produto, name="unidades_produto"),
    path("categorias/", views.categorias_produto, name="categorias_produto"),
    path("clientes/", views.clientes, name="clientes"),
    path("clientes/consulta/", views.clientes_consulta, name="clientes_consulta"),
    path("clientes/verificar-duplicado/", views.verificar_cliente_duplicado, name="verificar_cliente_duplicado"),
    path("clientes/autocomplete/", views.clientes_autocomplete, name="clientes_autocomplete"),
    path("clientes/<int:cliente_id>/cobranca-imagem/", views.cliente_cobranca_imagem, name="cliente_cobranca_imagem"),
    path("funcionarios/", views.funcionarios, name="funcionarios"),
    path("fornecedores/", views.fornecedores, name="fornecedores"),
    path("fornecedores/novo/", views.fornecedor_novo, name="fornecedor_novo"),
    path("fornecedores/<int:pk>/editar/", views.fornecedor_editar, name="fornecedor_editar"),
    path("cartoes/", views.meios_pagamento, name="cartoes"),
    path("meios-pagamento/", views.meios_pagamento, name="meios_pagamento"),
    path("compras/", views.compras_lista, name="compras_lista"),
    path("compras/nova/", views.compras_nova, name="compras_nova"),
    path("compras/nova/produto-rapido/", views.compra_produto_rapido_nova, name="compra_produto_rapido_nova"),
    path("compras/sugestao-fornecedor/", views.sugestao_compra_fornecedor, name="sugestao_compra_fornecedor"),
    path("compras/sugestao-fornecedor/whatsapp/", views.sugestao_compra_fornecedor_whatsapp, name="sugestao_compra_fornecedor_whatsapp"),
    path("compras/listas-fornecedor/", views.compras_listas_fornecedor, name="compras_listas_fornecedor"),
    path("compras/listas-fornecedor/gravar/", views.compras_lista_fornecedor_gravar, name="compras_lista_fornecedor_gravar"),
    path(
        "checklist/<path:token>/",
        views.compras_lista_fornecedor_conferencia_externa,
        name="checklist_conferencia_externa",
    ),
    path(
        "compras/listas-fornecedor/conferencia-externa/<path:token>/",
        views.compras_lista_fornecedor_conferencia_externa,
        name="compras_lista_fornecedor_conferencia_externa",
    ),
    path("compras/listas-fornecedor/<int:pk>/ver/", views.compras_lista_fornecedor_ver, name="compras_lista_fornecedor_ver"),
    path("compras/listas-fornecedor/<int:pk>/editar/", views.compras_lista_fornecedor_editar, name="compras_lista_fornecedor_editar"),
    path("compras/listas-fornecedor/<int:pk>/", views.compras_lista_fornecedor_detalhe, name="compras_lista_fornecedor_detalhe"),
    path("compras/listas-fornecedor/<int:pk>/conferencia/salvar/", views.compras_lista_fornecedor_conferencia_salvar, name="compras_lista_fornecedor_conferencia_salvar"),
    path("compras/listas-fornecedor/<int:pk>/whatsapp/", views.compras_lista_fornecedor_whatsapp, name="compras_lista_fornecedor_whatsapp"),
    path("compras/listas-fornecedor/<int:pk>/whatsapp/destinatario-recente/", views.compras_lista_fornecedor_whatsapp_destinatario_recente, name="compras_lista_fornecedor_whatsapp_destinatario_recente"),
    path("compras/listas-fornecedor/<int:pk>/confirmar-envio-vendedor/", views.compras_lista_fornecedor_confirmar_envio_vendedor, name="compras_lista_fornecedor_confirmar_envio_vendedor"),
    path("compras/listas-fornecedor/<int:pk>/whatsapp-imagem/", views.compras_lista_fornecedor_whatsapp_imagem, name="compras_lista_fornecedor_whatsapp_imagem"),
    path("compras/listas-fornecedor/<int:pk>/gerar-compra/", views.compras_lista_fornecedor_gerar_compra, name="compras_lista_fornecedor_gerar_compra"),
    path("compras/listas-fornecedor/<int:pk>/descartar-compra/", views.compras_lista_fornecedor_descartar_compra, name="compras_lista_fornecedor_descartar_compra"),
    path("compras/listas-fornecedor/<int:pk>/cancelar/", views.compras_lista_fornecedor_cancelar, name="compras_lista_fornecedor_cancelar"),
    path("fornecedores/<int:fornecedor_id>/contas-pagar-abertas/", views.fornecedor_contas_pagar_abertas, name="fornecedor_contas_pagar_abertas"),
    path("contas-pagar/<int:pk>/baixar/", views.conta_pagar_baixar, name="conta_pagar_baixar"),
    path("compras/<int:pk>/", views.compras_detalhe, name="compras_detalhe"),
    path("compras/<int:pk>/editar/", views.compra_editar, name="compra_editar"),
    path("compras/<int:pk>/finalizar/", views.compra_finalizar, name="compra_finalizar"),
    path("compras/<int:pk>/produto-rapido/", views.compra_produto_rapido, name="compra_produto_rapido"),
    path("compras/<int:pk>/corrigir-itens/", views.compra_corrigir_itens, name="compra_corrigir_itens"),
    path("compras/<int:pk>/corrigir-financeiro/", views.compra_corrigir_financeiro, name="compra_corrigir_financeiro"),
    path("compras/<int:pk>/corrigir-origem-pagamento/", views.compra_corrigir_origem_pagamento, name="compra_corrigir_origem_pagamento"),
    path("compras/<int:pk>/excluir/", views.compra_excluir, name="compra_excluir"),
    path("produtos/<int:produto_id>/ultimas-compras/", views.produto_ultimas_compras, name="produto_ultimas_compras"),
    path("verificar-produto/", views.verificar_produto, name="verificar_produto"),
    path("produto/<int:pk>/", views.produto_detalhe, name="produto_detalhe"),
    path("produto/<int:pk>/editar/", views.produto_editar, name="produto_editar"),
    path("vendas/", views.vendas, name="vendas"),
    path("vendas/consultar/", views.consultar_vendas, name="consultar_vendas"),
    path("vendas/consultar/canceladas/", views.consultar_vendas_canceladas, name="consultar_vendas_canceladas"),
    path("vendas/cliente-produto-historico/", views.vendas_cliente_produto_historico, name="vendas_cliente_produto_historico"),
    path("vendas/gravar/", views.gravar_venda, name="gravar_venda"),
    path("contas-a-receber/", views.contas_receber, name="contas_receber"),
    path("contas-a-pagar/", views.contas_pagar, name="contas_pagar"),
    path("pagar-fornecedor/", views.pagar_fornecedor, name="pagar_fornecedor"),
    path("contas-a-pagar/abertas/", views.contas_pagar_abertas_geral, name="contas_pagar_abertas_geral"),
    path("emprestimos-rapidos/", views.emprestimos_rapidos, name="emprestimos_rapidos"),
    path("emprestimos-dividas/", views.emprestimos_dividas, name="emprestimos_dividas"),
    path("emprestimos-dividas/nova/", views.emprestimo_divida_nova, name="emprestimo_divida_nova"),
    path("emprestimos-dividas/<int:pk>/", views.emprestimo_divida_detalhe, name="emprestimo_divida_detalhe"),
    path("emprestimos-dividas/<int:pk>/baixar/", views.emprestimo_divida_baixar, name="emprestimo_divida_baixar"),
    path("receber-cliente/", views.receber_cliente_escolher, name="receber_cliente_escolher"),
    path("central-pix/", views.central_pix, name="central_pix"),
    path("pix/enviar/", views.pix_enviar_inteligente, name="pix_enviar_inteligente"),
    path("central-pix/enviar-comprovante/", views.central_pix_enviar_comprovante, name="central_pix_enviar_comprovante"),
    path("central-pix/envio-sucesso/<int:pix_id>/", views.central_pix_envio_sucesso, name="central_pix_envio_sucesso"),
    path("central-pix/<int:pix_id>/comprovante/", views.central_pix_comprovante, name="central_pix_comprovante"),
    path("central-pix/<int:pix_id>/processar-ocr/", views.central_pix_processar_ocr, name="central_pix_processar_ocr"),
    path("central-pix/<int:pix_id>/remover-cliente-confirmado/", views.central_pix_remover_cliente_confirmado, name="central_pix_remover_cliente_confirmado"),
    path("central-pix/<int:pix_id>/excluir/", views.central_pix_excluir, name="central_pix_excluir"),
    path("central-pix/<int:pix_id>/", views.central_pix_detalhe, name="central_pix_detalhe"),
    path("central-pix/analisar-comprovante/", views.central_pix_analisar_comprovante, name="central_pix_analisar_comprovante"),
    path("contas-a-receber/cliente/<int:cliente_id>/receber/", views.receber_cliente, name="receber_cliente"),
    path("contas-a-receber/cliente/<int:cliente_id>/comprovante/<str:token>/imagem/", views.receber_cliente_comprovante_imagem, name="receber_cliente_comprovante_imagem"),
    path("contas-a-receber/creditos/cliente/<int:cliente_id>/", views.cliente_credito_detalhe, name="cliente_credito_detalhe"),
    path("contas-a-receber/<int:pk>/receber/", views.conta_receber_receber, name="conta_receber_receber"),
    path("entregas/", views.entregas_dia, name="entregas_dia"),
    path("entregas/pendencias/", views.pendencias_entrega, name="pendencias_entrega"),
    path("entregas/pendencias/<int:checklist_id>/remover-da-nota/", views.revisar_remocao_pendencia_da_nota, name="revisar_remocao_pendencia_da_nota"),
    path("entregas/<int:pk>/", views.entrega_rota_detalhe, name="entrega_rota_detalhe"),
    path("entregas/<int:pk>/excluir/", views.entrega_rota_excluir, name="entrega_rota_excluir"),
    path("entregas/<int:pk>/checklist/", views.entrega_rota_checklist, name="entrega_rota_checklist"),
    path("entregas/<int:rota_id>/checklist/item/<int:rota_item_id>/", views.entrega_rota_checklist_cliente, name="entrega_rota_checklist_item"),
    path("entregas/<int:rota_id>/checklist/cliente/<int:venda_id>/", views.entrega_rota_checklist_cliente, name="entrega_rota_checklist_cliente"),
    path("vendas/<int:pk>/editar/", views.venda_editar_revisao, name="venda_editar_revisao"),
    path("vendas/<int:pk>/editar/cabecalho/", views.venda_editar_cabecalho, name="venda_editar_cabecalho"),
    path("vendas/<int:pk>/editar/adicionar-produto/", views.venda_adicionar_produto_item, name="venda_adicionar_produto_item"),
    path("vendas/<int:pk>/editar/item/<int:item_id>/quantidade/", views.venda_editar_quantidade_item, name="venda_editar_quantidade_item"),
    path("vendas/<int:pk>/editar/item/<int:item_id>/remover/", views.venda_revisar_remocao_item, name="venda_revisar_remocao_item"),
    path("vendas/<int:pk>/editar/remocao/<int:remocao_id>/desfazer/", views.venda_desfazer_remocao_item, name="venda_desfazer_remocao_item"),
    path("vendas/<int:pk>/ajuste-item-quitado/", views.venda_ajuste_item_quitado, name="venda_ajuste_item_quitado"),
    path("vendas/<int:pk>/ajuste-item-quitado/<int:ajuste_id>/credito/", views.venda_ajuste_item_quitado_credito, name="venda_ajuste_item_quitado_credito"),
    path("vendas/<int:pk>/cancelar/", views.venda_cancelar, name="venda_cancelar"),
    path("vendas/<int:pk>/cliente/", views.venda_cliente_detalhe, name="venda_cliente_detalhe"),
    path("vendas/<int:pk>/", views.venda_detalhe, name="venda_detalhe"),
    path("vendas/<int:pk>/criar-entrega/", views.venda_criar_entrega, name="venda_criar_entrega"),
    path("vendas/<int:pk>/whatsapp-imagem/", views.venda_whatsapp_imagem, name="venda_whatsapp_imagem"),
    path("vendas/<int:pk>/whatsapp-pdf/", views.venda_whatsapp_pdf, name="venda_whatsapp_pdf"),
    path("vendas/<int:pk>/preparar-whatsapp/", views.preparar_whatsapp_venda, name="preparar_whatsapp_venda"),
    path("vendas/<int:pk>/registrar-impressao/", views.registrar_impressao, name="registrar_impressao"),
    path("vendas/<int:pk>/registrar-whatsapp-aberto/", views.registrar_whatsapp_aberto, name="registrar_whatsapp_aberto"),
    path("vendas/<int:pk>/registrar-checklist-whatsapp-aberto/", views.registrar_checklist_whatsapp_aberto, name="registrar_checklist_whatsapp_aberto"),
    path("vendas/<int:pk>/confirmar-checklist-whatsapp/", views.confirmar_checklist_whatsapp, name="confirmar_checklist_whatsapp"),
    path("vendas/<int:pk>/confirmar-whatsapp/", views.confirmar_whatsapp, name="confirmar_whatsapp"),
    path("excluir/<int:pk>/", views.produto_excluir, name="produto_excluir"),
    path("lixeira/", views.lixeira, name="lixeira"),
    path("restaurar/<int:pk>/", views.produto_restaurar, name="produto_restaurar"),
    path("excluir-definitivo/<int:pk>/", views.produto_excluir_definitivo, name="produto_excluir_definitivo"),
    # Rotas de Pedidos
    path("pedidos/", views.pedidos, name="pedidos"),
    path("pedidos/criar/", views.pedido_criar, name="pedido_criar"),
    path("pedidos/<int:pk>/editar/", views.pedido_editar, name="pedido_editar"),
    path("pedidos/<int:pk>/cancelar/", views.pedido_cancelar, name="pedido_cancelar"),
    path("pedidos/<int:pk>/", views.pedido_detalhe, name="pedido_detalhe"),
]
