# Generated by Django 6.0.1 on 2026-07-31 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0007_tarefaoperacionallocacao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefaoperacionallocacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Entrega parcial'), ('confirmada', 'Confirmada'), ('nao_possivel', 'Nao foi possivel realizar')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='ConferenciaEntregaLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsto_mesas', models.PositiveIntegerField()),
                ('previsto_cadeiras', models.PositiveIntegerField()),
                ('entregue_mesas', models.PositiveIntegerField()),
                ('entregue_cadeiras', models.PositiveIntegerField()),
                ('acumulado_mesas', models.PositiveIntegerField()),
                ('acumulado_cadeiras', models.PositiveIntegerField()),
                ('pendente_mesas', models.PositiveIntegerField()),
                ('pendente_cadeiras', models.PositiveIntegerField()),
                ('situacao', models.CharField(choices=[('parcial', 'Entrega parcial'), ('completa', 'Entrega completa')], max_length=20)),
                ('recebedor_nome', models.CharField(max_length=160)),
                ('recebedor_relacao', models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionario'), ('caseiro', 'Caseiro'), ('familiar', 'Familiar'), ('outro', 'Outro')], max_length=20)),
                ('recebedor_relacao_outro', models.CharField(blank=True, max_length=120)),
                ('estado_material', models.CharField(choices=[('bom', 'Em bom estado'), ('ressalva', 'Entregue com ressalva')], max_length=20)),
                ('justificativa_parcial', models.TextField(blank=True)),
                ('previsao_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('responsavel', models.CharField(max_length=120)),
                ('mensagem_whatsapp_snapshot', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias_entrega', to='locacoes.locacao')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_entrega', to='locacoes.tarefaoperacionallocacao')),
            ],
            options={
                'verbose_name': 'Conferencia de entrega de locacao',
                'verbose_name_plural': 'Conferencias de entrega de locacao',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
