# Generated by Django 6.0.1 on 2026-07-31 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0008_alter_tarefaoperacionallocacao_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarefaoperacionallocacao',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('parcial', 'Parcial'), ('confirmada', 'Confirmada'), ('nao_possivel', 'Nao foi possivel realizar')], default='pendente', max_length=20),
        ),
        migrations.CreateModel(
            name='ConferenciaRecolhimentoLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previsto_mesas', models.PositiveIntegerField()),
                ('previsto_cadeiras', models.PositiveIntegerField()),
                ('boa_mesas', models.PositiveIntegerField(default=0)),
                ('boa_cadeiras', models.PositiveIntegerField(default=0)),
                ('quebrada_mesas', models.PositiveIntegerField(default=0)),
                ('quebrada_cadeiras', models.PositiveIntegerField(default=0)),
                ('perdida_mesas', models.PositiveIntegerField(default=0)),
                ('perdida_cadeiras', models.PositiveIntegerField(default=0)),
                ('descartada_mesas', models.PositiveIntegerField(default=0)),
                ('descartada_cadeiras', models.PositiveIntegerField(default=0)),
                ('acumulado_boa_mesas', models.PositiveIntegerField(default=0)),
                ('acumulado_boa_cadeiras', models.PositiveIntegerField(default=0)),
                ('acumulado_quebrada_mesas', models.PositiveIntegerField(default=0)),
                ('acumulado_quebrada_cadeiras', models.PositiveIntegerField(default=0)),
                ('acumulado_perdida_mesas', models.PositiveIntegerField(default=0)),
                ('acumulado_perdida_cadeiras', models.PositiveIntegerField(default=0)),
                ('acumulado_descartada_mesas', models.PositiveIntegerField(default=0)),
                ('acumulado_descartada_cadeiras', models.PositiveIntegerField(default=0)),
                ('pendente_mesas', models.PositiveIntegerField()),
                ('pendente_cadeiras', models.PositiveIntegerField()),
                ('situacao', models.CharField(choices=[('parcial', 'Recolhimento parcial'), ('completa', 'Recolhimento completo')], max_length=20)),
                ('pessoa_local_nome', models.CharField(max_length=160)),
                ('pessoa_local_relacao', models.CharField(choices=[('cliente', 'Cliente'), ('funcionario', 'Funcionario'), ('caseiro', 'Caseiro'), ('familiar', 'Familiar'), ('outro', 'Outro')], max_length=20)),
                ('pessoa_local_relacao_outro', models.CharField(blank=True, max_length=120)),
                ('justificativa_parcial', models.TextField(blank=True)),
                ('previsao_conclusao', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('responsavel', models.CharField(max_length=120)),
                ('mensagem_whatsapp_snapshot', models.TextField(blank=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('locacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conferencias_recolhimento', to='locacoes.locacao')),
                ('tarefa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conferencias_recolhimento', to='locacoes.tarefaoperacionallocacao')),
            ],
            options={
                'verbose_name': 'Conferencia de recolhimento de locacao',
                'verbose_name_plural': 'Conferencias de recolhimento de locacao',
                'ordering': ['-criado_em', '-id'],
            },
        ),
    ]
