# Generated by Django 6.0.1 on 2026-08-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0009_alter_tarefaoperacionallocacao_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentolocacao',
            name='recibo_token',
            field=models.UUIDField(blank=True, db_index=True, editable=False, null=True),
        ),
    ]
