# Generated by Django 6.0.1 on 2026-08-02 08:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locacoes', '0010_pagamentolocacao_recibo_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamentolocacao',
            name='recibo_token',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
