# Generated by Django 6.0.1 on 2026-09-18 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0105_itemvendaremovido_custo_origem_snapshot_and_more'),
        ('locacoes', '0012_conferencia_entrega_itens_contratados'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentolocacao',
            name='operacao_recebimento_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos_locacao', to='estoque.operacaorecebimentocliente'),
        ),
    ]
