# Generated by Django 6.0.1 on 2026-10-04 22:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locacoes', '0014_tarefa_resolucao_administrativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperacaoSincronizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_id', models.UUIDField(unique=True)),
                ('device_id', models.UUIDField()),
                ('environment_id', models.CharField(max_length=160)),
                ('type', models.CharField(max_length=60)),
                ('schema_version', models.PositiveSmallIntegerField()),
                ('aggregate_id', models.CharField(max_length=40)),
                ('payload', models.JSONField()),
                ('payload_hash', models.CharField(max_length=64)),
                ('comando', models.JSONField()),
                ('status', models.CharField(max_length=30)),
                ('resultado', models.JSONField(default=dict)),
                ('recebido_em', models.DateTimeField(auto_now_add=True)),
                ('concluido_em', models.DateTimeField(null=True)),
                ('erro', models.TextField(blank=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='locacoes.eventolocacao')),
            ],
            options={
                'permissions': [('registrar_observacao', 'Preparar e sincronizar observacoes offline')],
            },
        ),
    ]
