"""
Django settings for sistema project.

Generated by 'django-admin startproject' using Django 6.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


from decouple import config, Csv
import os

SECRET_KEY = config('SECRET_KEY')
DEBUG = str(config('DEBUG', default='False')).strip().lower() in {'1', 'true', 'yes', 'on', 'debug'}
ALLOWED_HOSTS = config('ALLOWED_HOSTS', default='', cast=Csv())
CSRF_TRUSTED_ORIGINS = config('CSRF_TRUSTED_ORIGINS', default='', cast=Csv())
CHECKLIST_BASE_URL = config("CHECKLIST_BASE_URL", default=os.getenv("CHECKLIST_BASE_URL", "")).rstrip("/")
SISTEMA_ONLINE_URL = config(
    "SISTEMA_ONLINE_URL",
    default=config("SISTEMA_RENDER_URL", default="https://sistema-de-vendas-e-estoque.onrender.com"),
).rstrip("/")
PIX_LOCAL_URL = config("PIX_LOCAL_URL", default="")
PIX_ONLINE_URL = config(
    "PIX_ONLINE_URL",
    default=f"{SISTEMA_ONLINE_URL}/central-pix/enviar-comprovante/",
)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'estoque',
    

]



MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sistema.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': { 
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'estoque.context_processors.ambiente_sistema',
            ],
        },
    },
]

WSGI_APPLICATION = 'sistema.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import dj_database_url

DATABASES = {
    'default': dj_database_url.parse(
        config('DATABASE_URL', default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
    )
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/Belem'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / "static",
]
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

USE_CLOUDFLARE_R2_STORAGE = str(config("USE_CLOUDFLARE_R2_STORAGE", default="False")).strip().lower() in {
    "1",
    "true",
    "yes",
    "on",
}
CLOUDFLARE_R2_ACCESS_KEY_ID = config("CLOUDFLARE_R2_ACCESS_KEY_ID", default="")
CLOUDFLARE_R2_SECRET_ACCESS_KEY = config("CLOUDFLARE_R2_SECRET_ACCESS_KEY", default="")
CLOUDFLARE_R2_BUCKET_NAME = config("CLOUDFLARE_R2_BUCKET_NAME", default="")
CLOUDFLARE_R2_ENDPOINT_URL = config("CLOUDFLARE_R2_ENDPOINT_URL", default="")
CLOUDFLARE_R2_REGION_NAME = config("CLOUDFLARE_R2_REGION_NAME", default="auto")
CLOUDFLARE_R2_CUSTOM_DOMAIN = config("CLOUDFLARE_R2_CUSTOM_DOMAIN", default="")
CLOUDFLARE_R2_QUERYSTRING_AUTH = str(
    config("CLOUDFLARE_R2_QUERYSTRING_AUTH", default="True")
).strip().lower() in {"1", "true", "yes", "on"}
CLOUDFLARE_R2_ENABLED = USE_CLOUDFLARE_R2_STORAGE and all(
    [
        CLOUDFLARE_R2_ACCESS_KEY_ID,
        CLOUDFLARE_R2_SECRET_ACCESS_KEY,
        CLOUDFLARE_R2_BUCKET_NAME,
        CLOUDFLARE_R2_ENDPOINT_URL,
    ]
)
STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

if CLOUDFLARE_R2_ENABLED:
    r2_options = {
        "access_key": CLOUDFLARE_R2_ACCESS_KEY_ID,
        "secret_key": CLOUDFLARE_R2_SECRET_ACCESS_KEY,
        "bucket_name": CLOUDFLARE_R2_BUCKET_NAME,
        "endpoint_url": CLOUDFLARE_R2_ENDPOINT_URL,
        "region_name": CLOUDFLARE_R2_REGION_NAME,
        "default_acl": None,
        "file_overwrite": False,
        "querystring_auth": CLOUDFLARE_R2_QUERYSTRING_AUTH,
    }
    if CLOUDFLARE_R2_CUSTOM_DOMAIN:
        r2_options["custom_domain"] = CLOUDFLARE_R2_CUSTOM_DOMAIN
    STORAGES["default"] = {
        "BACKEND": "storages.backends.s3.S3Storage",
        "OPTIONS": r2_options,
    }

if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = "DENY"
